# fly.toml file generated for yoga-forum on 2022-04-10T18:33:36-04:00

app = "yoga-forum-test"

[[services]]
internal_port = 8080
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = "80"
force_https = true

[[services.ports]]
handlers = ["tls", "http"]
port = "443"
